service: aws-email-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: ProgrammaticAccess
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ses:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events: # All events associated with this function
      - http:
          path: hello-test
          method: GET
          cors: true
  sendEmail:
    handler: sendEmail.handler # Path to the function (fileName.exportFunction)
    events:
      - http:
          path: send-email
          method: POST
          cors: true